/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      danger: '#E24B4A',
      'on-secondary-fixed': '#150264',
      surface: '#FFFFFF',
      outline: '#6d7a73',
      'on-secondary-container': '#3d358a',
      'on-error': '#ffffff',
      'primary-fixed': '#86f8c9',
      'secondary-container': '#aba3ff',
      'inverse-surface': '#2f3130',
      'on-surface-variant': '#3d4943',
      'on-tertiary-container': '#fdfcff',
      'primary-container': '#008560',
      'on-error-container': '#93000a',
      'on-secondary-fixed-variant': '#423a8f',
      tertiary: '#145da3',
      'on-tertiary': '#ffffff',
      'surface-container-high': '#e8e8e6',
      'surface-container': '#eeeeec',
      'surface-variant': '#e2e3e1',
      error: '#ba1a1a',
      'surface-container-low': '#f4f4f2',
      'secondary-fixed-dim': '#c5c0ff',
      'on-tertiary-fixed': '#001c39',
      'tertiary-container': '#3976be',
      'on-secondary': '#ffffff',
      'text-main': '#1A1C1E',
      'surface-dim': '#dadad8',
      'on-primary-fixed': '#002115',
      'on-tertiary-fixed-variant': '#004883',
      background: '#f9f9f7',
      'surface-container-highest': '#e2e3e1',
      'outline-variant': '#bccac1',
      'error-container': '#ffdad6',
      secondary: '#5a53a9',
      'on-primary-container': '#f5fff7',
      primary: '#00694c',
      'on-primary': '#ffffff',
      'inverse-on-surface': '#f1f1ef',
      'tertiary-fixed-dim': '#a4c9ff',
      'surface-container-lowest': '#ffffff',
      'on-background': '#1a1c1b',
      'surface-bright': '#f9f9f7',
      'on-surface': '#1a1c1b',
      'on-primary-fixed-variant': '#00513a',
      'primary-fixed-dim': '#68dbae',
      'surface-tint': '#006c4e',
      warning: '#EF9F27',
      'tertiary-fixed': '#d4e3ff',
      'text-muted': '#64748B',
      'secondary-fixed': '#e4dfff',
      'inverse-primary': '#68dbae',
      white: '#ffffff',
      gray: {
        50: '#f9fafb',
        100: '#f3f4f6',
        200: '#e5e7eb',
        400: '#9ca3af',
        500: '#6b7280',
        600: '#4b5563',
        800: '#1f2937',
        900: '#111827',
        950: '#030712',
      },
      black: '#000000',
      transparent: 'transparent',
    },
    extend: {
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        base: '8px',
        'touch-target-min': '44px',
        'container-padding': '20px',
        'grid-gutter': '16px',
        'panel-gap': '24px',
      },
      fontFamily: {
        sans: 'Inter, sans-serif',
      },
      fontSize: {
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'h2': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'currency-display': ['28px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
};
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      danger: '#E24B4A',
      'on-secondary-fixed': '#150264',
      surface: '#FFFFFF',
      outline: '#6d7a73',
      'on-secondary-container': '#3d358a',
      'on-error': '#ffffff',
      'primary-fixed': '#86f8c9',
      'secondary-container': '#aba3ff',
      'inverse-surface': '#2f3130',
      'on-surface-variant': '#3d4943',
      'on-tertiary-container': '#fdfcff',
      'primary-container': '#008560',
      'on-error-container': '#93000a',
      'on-secondary-fixed-variant': '#423a8f',
      tertiary: '#145da3',
      'on-tertiary': '#ffffff',
      'surface-container-high': '#e8e8e6',
      'surface-container': '#eeeeec',
      'surface-variant': '#e2e3e1',
      error: '#ba1a1a',
      'surface-container-low': '#f4f4f2',
      'secondary-fixed-dim': '#c5c0ff',
      'on-tertiary-fixed': '#001c39',
      'tertiary-container': '#3976be',
      'on-secondary': '#ffffff',
      'text-main': '#1A1C1E',
      'surface-dim': '#dadad8',
      'on-primary-fixed': '#002115',
      'on-tertiary-fixed-variant': '#004883',
      background: '#f9f9f7',
      'surface-container-highest': '#e2e3e1',
      'outline-variant': '#bccac1',
      'error-container': '#ffdad6',
      secondary: '#5a53a9',
      'on-primary-container': '#f5fff7',
      primary: '#00694c',
      'on-primary': '#ffffff',
      'inverse-on-surface': '#f1f1ef',
      'tertiary-fixed-dim': '#a4c9ff',
      'surface-container-lowest': '#ffffff',
      'on-background': '#1a1c1b',
      'surface-bright': '#f9f9f7',
      'on-surface': '#1a1c1b',
      'on-primary-fixed-variant': '#00513a',
      'primary-fixed-dim': '#68dbae',
      'surface-tint': '#006c4e',
      warning: '#EF9F27',
      'tertiary-fixed': '#d4e3ff',
      'text-muted': '#64748B',
      'secondary-fixed': '#e4dfff',
      'inverse-primary': '#68dbae',
      white: '#ffffff',
      gray: {
        50: '#f9fafb',
        100: '#f3f4f6',
        200: '#e5e7eb',
        400: '#9ca3af',
        500: '#6b7280',
        600: '#4b5563',
        800: '#1f2937',
        900: '#111827',
        950: '#030712',
      },
      black: '#000000',
      transparent: 'transparent',
    },
    extend: {
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        base: '8px',
        'touch-target-min': '44px',
        'container-padding': '20px',
        'grid-gutter': '16px',
        'panel-gap': '24px',
      },
      fontFamily: {
        sans: 'Inter, sans-serif',
      },
      fontSize: {
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'h2': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'currency-display': ['28px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
};

